### ISSUE TITLE
Nickolas-Reverendo-CH needs to update caption

### ISSUE THREAD

**Issue by Nickolas-Reverendo-CH** [cigna-eval-saas/march-23#9]
**TODO:**
 - [x] update the slide caption
 - [x] verify/update the image
 - [x] update the title
